simple_mapping:
  ros__parameters:
    # use_sim_time: true
    # leishen16
    laser:
        odom_type: "wheel_odometry"         #wheel_odometry/laser_odometry 
        baselink_frame: "base_link"
        num_vertical_scans: 32
        num_horizontal_scans: 640
        ground_scan_index: 15
        # vertical_angle_bottom: -7.0          # degrees
        # vertical_angle_top: 52.0            # degrees
        vertical_angle_bottom: -40.0          # degrees
        vertical_angle_top: 40.0            # degrees
        scan_period: 0.1                   # seconds

    imageProjection:
        segment_valid_point_num: 5
        segment_valid_line_num: 2
        segment_theta: 60.0                      # decrese this value may improve accuracy
        minimum_detection_range: 0.5
        maximum_detection_range: 100.0            # point cloud within this range will be used to project image
        distance_for_patch_between_rings: 1.0    # patch ground between rings within this range, i.e. ring0 and ring1 is smaller than 1 meter, patch them
        stitcher_num: 3

    mapping:

        keyframe_distance_threshold: 1.0
        keyframe_angle_threshold: 1.0
        
        map_resolution: 0.3
        ground_resolution: 0.3